import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import path from 'node:path';
import fs from 'node:fs';
import fsPromises from 'node:fs/promises';
import { spawn } from 'node:child_process';
import { createE2EContext } from './utils.js';

const { runCli, e2eDir, setupE2E, teardownE2E } = createE2EContext('e2e-tmp-requests');

describe('E2E Requests Tests (Lite)', () => {
  let litePath = '';
  let envUrl = '';
  let envToken = '';

  beforeAll(async () => {
    await setupE2E();
    await runCli(['init']);

    // Setup policies.json
    const policiesPath = path.join(e2eDir, '.clawmini', 'policies.json');
    await fsPromises.writeFile(
      policiesPath,
      JSON.stringify({
        policies: {
          'test-cmd': {
            description: 'A test policy',
            command: 'echo',
            args: ['hello'],
            allowHelp: true,
          },
          'no-help-cmd': {
            description: 'A no help policy',
            command: 'echo',
            args: ['nohelp'],
          },
        },
      })
    );

    // Setup daemon with API enabled
    const settingsPath = path.resolve(e2eDir, '.clawmini/settings.json');
    let originalSettings = '{}';
    if (fs.existsSync(settingsPath)) {
      originalSettings = fs.readFileSync(settingsPath, 'utf8');
    }
    fs.writeFileSync(
      settingsPath,
      JSON.stringify({
        ...JSON.parse(originalSettings),
        api: { host: '127.0.0.1', port: 3008 },
      })
    );
    await runCli(['up']);

    // Export lite script
    litePath = path.resolve(e2eDir, 'clawmini-lite.js');
    await runCli(['export-lite', '--out', litePath]);

    // Setup env-dumper agent
    const envDumperAgentDir = path.resolve(e2eDir, 'lite-env-dumper');
    fs.mkdirSync(envDumperAgentDir, { recursive: true });
    await runCli(['agents', 'add', 'lite-env-dumper', '--dir', 'lite-env-dumper']);

    const dumperSettings = path.resolve(e2eDir, '.clawmini/agents/lite-env-dumper/settings.json');
    fs.mkdirSync(path.dirname(dumperSettings), { recursive: true });
    const dumperScript = process.platform === 'win32' ? 'set > env.txt' : 'env > env.txt';
    fs.writeFileSync(dumperSettings, JSON.stringify({ commands: { new: dumperScript } }));

    await runCli(['chats', 'add', 'lite-chat']);
    await runCli(['messages', 'send', 'dump', '--chat', 'lite-chat', '--agent', 'lite-env-dumper']);

    await new Promise((resolve) => setTimeout(resolve, 3000));

    const envTxtPath = path.resolve(envDumperAgentDir, 'env.txt');
    if (!fs.existsSync(envTxtPath)) {
      throw new Error('env.txt not generated by agent');
    }
    const envContent = fs.readFileSync(envTxtPath, 'utf8');
    const urlMatch = envContent.match(/CLAW_API_URL=(.+)/);
    const tokenMatch = envContent.match(/CLAW_API_TOKEN=(.+)/);

    if (!urlMatch || !tokenMatch) {
      throw new Error('Could not find API credentials');
    }

    envUrl = urlMatch[1]!.trim();
    envToken = tokenMatch[1]!.trim();
  }, 30000);

  afterAll(teardownE2E, 30000);

  function runLite(
    args: string[]
  ): Promise<{ stdout: string; stderr: string; code: number | null }> {
    return new Promise((resolve) => {
      const p = spawn('node', [litePath, ...args], {
        env: { ...process.env, CLAW_API_URL: envUrl, CLAW_API_TOKEN: envToken },
        cwd: e2eDir,
      });
      let stdout = '';
      let stderr = '';
      p.stdout.on('data', (d) => (stdout += d.toString()));
      p.stderr.on('data', (d) => (stderr += d.toString()));
      p.on('close', (code) => resolve({ stdout, stderr, code }));
    });
  }

  it('should list policies', async () => {
    const { stdout, code } = await runLite(['requests', 'list']);
    expect(code).toBe(0);
    expect(stdout).toContain('Available Policies:');
    expect(stdout).toContain('- test-cmd');
    expect(stdout).toContain('Description: A test policy');
  });

  it('should run --help on underlying command', async () => {
    const { stdout, code } = await runLite(['request', 'test-cmd', '--help']);
    expect(code).toBe(0);
    expect(stdout).toBeTruthy();
  });

  it('should block --help if allowHelp is not true', async () => {
    const { stderr, code } = await runLite(['request', 'no-help-cmd', '--help']);
    expect(code).toBe(1);
    expect(stderr).toContain('This command does not support --help');
  });

  it('should create a request and return an ID', async () => {
    const dummyFilePath = path.join(e2eDir, 'lite-env-dumper', 'dummy.txt');
    await fsPromises.writeFile(dummyFilePath, 'dummy content');

    const { stdout, stderr, code } = await runLite([
      'request',
      'test-cmd',
      '--file',
      `target=${dummyFilePath}`,
      '--',
      'extra1',
      'extra2',
    ]);

    expect(stderr).toBe('');
    expect(code).toBe(0);
    expect(stdout).toContain('Request created successfully.');
    expect(stdout).toContain('Request ID:');

    // Verify the request was saved
    const requestsDir = path.join(e2eDir, '.clawmini', 'tmp', 'requests');
    const files = await fsPromises.readdir(requestsDir);
    const jsonFiles = files.filter((f) => f.endsWith('.json'));
    expect(jsonFiles.length).toBe(1);

    const reqData = await fsPromises.readFile(path.join(requestsDir, jsonFiles[0]!), 'utf8');
    const req = JSON.parse(reqData);

    expect(req.commandName).toBe('test-cmd');
    expect(req.args).toEqual(['extra1', 'extra2']);
    expect(req.fileMappings).toHaveProperty('target');

    // Check snapshot exists
    const snapshotPath = req.fileMappings.target;
    const snapshotContent = await fsPromises.readFile(snapshotPath, 'utf8');
    expect(snapshotContent).toBe('dummy content');
  });
});
